import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Navigation } from './components/Navigation'

// If loading a variable font, you don't need to specify the font weight
const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MyFirst Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
